path: roadsigns  # dataset root dir
train: images/train  # train images
val: images/val  # val images
test:  images/test # test images (optional)

# Classes
names:
  0:  trafficlight
  1:  stop
  2:  speedlimit
  3:  crosswalk
