path: kitti
train: images/train
val: images/val

names:
  0: car
  1: person
  2: van
  3: rider
  4: truck
  5: tram
  6: bus
  7: train
  8: motorcycle
  9: bicycle
  10: traffic light
  11: street sign
